baseURL = "https://rusttalk.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "en"
hasCJKLanguage = true
title = "RustTalk"
theme = "zen"
copyright = "2022 rusttalk.github.io"
googleAnalytics = "UA-50745138-4"
paginate = 10
paginatePath = "page"
enableGitInfo = true

[frontmatter]
  lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[author]
    name = "å†™ä»£ç çš„è¥¿ç“œ"
    email = "rusttalk@liujiacai.net"

[[menu.main]]
  name = "æ’­å®¢"
  weight = 20
  identifier = "podcast"
  url = "/podcast/"
[[menu.main]]
  name = "æ ‡ç­¾"
  weight = 22
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "å…³äº"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "ğŸ”¥ çˆ±å‘ç”µ ğŸ”¥"
  weight = 50
  identifier = "afdian"
  url = "/donate"

[params]
    logo = true
    mainSections = ["post", "podcast"]
    fadian = """
#### å…¬å‘Šæ  -- Bulletin Board
1. æ‹›å‹Ÿ [Podcast å˜‰å®¾](https://github.com/rusttalk/guests)ï¼Œåˆ†äº«æ‚¨ä¸ Rust çš„æ•…äº‹
2. å¦‚æœ RustTalk å¯¹æ‚¨æœ‰æ‰€å¸®åŠ©ï¼Œæ¬¢è¿è¿›è¡Œ[å‘ç”µæ”¯æŒ](/donate) â¤ï¸
"""
    dateformat = "2006-01-02"
    description = "RustTalk æ˜¯ä¸€æ¡£ä¸“æ³¨åœ¨ Rust ç¤¾åŒºçš„ç¨‹åºå‘˜é—²èŠèŠ‚ç›®ã€‚å®˜ç½‘ï¼šrusttalk.github.io"
    feedlinks = false
    realfavicongenerator = true
    relatedposts = true
    submitted = true
    sidebar = true
    mobileMenu = true
    copyright = "Â© 2022 [RustTalk](https://github.com/RustTalk/rusttalk.github.io) Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    poweredby = true
    # footer = "footer"
    [params.podcast]
        local = false
        image = "logo3000.png"
        lang = "zh-cn"
        author = "å†™ä»£ç çš„è¥¿ç“œ"
        [params.podcast.category]
            name = "Technology"
        [params.podcast.owner]
            name = "å†™ä»£ç çš„è¥¿ç“œ"
            email = "jiacai2050@gmail.com"
