baseURL = "https://rusttalk.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "en"
hasCJKLanguage = true
title = "RustTalk"
theme = "zen"
copyright = "2022 rusttalk.github.io"
googleAnalytics = "UA-50745138-4"
paginate = 10
paginatePath = "page"
enableGitInfo = true

[frontmatter]
  lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[author]
    name = "å†™ä»£ç çš„è¥¿ç“œ"
    email = "rusttalk@liujiacai.net"

[[menu.main]]
  name = "æ’­å®¢"
  weight = 20
  identifier = "podcast"
  url = "/podcast/"
# [[menu.main]]
#   name = "æ ‡ç­¾"
#   weight = 22
#   identifier = "tags"
#   url = "/tags/"
[[menu.main]]
  name = "å…³äº"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "æ‰“èµ"
  weight = 50
  identifier = "afdian"
  url = "https://liujiacai.net/donate/"

[params]
    logo = true
    mainSections = ["post", "podcast"]
    git_repo = "https://github.com/RustTalk/rusttalk.github.io"
    fadian = """
#### æ¬¢è¿å¬ä¼—[æ‰“èµæ”¯æŒ](https://liujiacai.net/donate/)ï¼Œæ‚¨çš„æ”¯æŒæ˜¯æˆ‘ä¸æ–­åˆ›ä½œçš„åŠ¨åŠ›ğŸ»
"""
    dateformat = "2006-01-02"
    description = "RustTalk æ˜¯ä¸€æ¡£ä¸“æ³¨åœ¨ Rust ç¤¾åŒºçš„ç¨‹åºå‘˜é—²èŠèŠ‚ç›®ã€‚å®˜ç½‘ï¼šrusttalk.github.io"
    feedlinks = false
    realfavicongenerator = true
    relatedposts = true
    submitted = true
    sidebar = true
    mobileMenu = true
    copyright = "Â© 2022 [RustTalk](https://github.com/RustTalk/rusttalk.github.io) Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    poweredby = true
    # footer = "footer"
    [params.giscus]           # https://giscus.app/
        repo = "RustTalk/rusttalk.github.io"
        repoId = "R_kgDOGm5vDQ"
        category = "Announcements"
        categoryId = "DIC_kwDOGm5vDc4CSRaH"
    [params.podcast]
        local = false
        image = "logo3000.png"
        lang = "zh-cn"
        author = "å†™ä»£ç çš„è¥¿ç“œ"
        [params.podcast.category]
            name = "Technology"
        [params.podcast.owner]
            name = "å†™ä»£ç çš„è¥¿ç“œ"
            email = "jiacai2050@gmail.com"
